layout: sidebar
style: light
# include: ['_pages']

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

# github: [metadata]

defaults:
  - 
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
      # - personal-website

social_media:
  # facebook: jessiedavis
  linkedin: jessica-davis-b4926087
  # stackoverflow: 7303311
  twitter: gleibryn
  youtube: UC4eBzJpxkKRUR15lgLkpvzw

topics:
  - name: Flutter
    web_url: https://flutter.io
  
  - name: Flare
    web_url: https://www.2dimensions.com/
  
  - name: Animation
  - name: VR/AR
  - name: Gaming

  # - name: Flutter
  #   web_url: https://github.com/topics/flutter
  #   image_url: /assets/images/flutter/logo.jpg
